apiVersion: v1
kind: Service
metadata:
  name: loki-network
  labels:
    app: loki-network
spec:
  type: NodePort 
  ports:
    - protocol: UDP 
      port: 1090 
      name: udp-1
      targetPort: 1090 
    - protocol: UDP 
      port: 1190 
      name: udp-2
      targetPort: 1190 
  selector:
    app: loki-network
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: loki-network lokinet
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/notify: deployments # chat channels to sent notification to
  generation: 1
  labels:
    app: loki-network
    keel.sh/policy: force # update policy (available: patch, minor, major, all, force)
    keel.sh/trigger: poll # enable active repository checking (webhooks and GCR would still work)
    keel.sh/approvals: "0" # required approvals to update
    keel.sh/match-tag: "true" # only makes a difference when used with 'force' policy, will only update if tag matches :dev->:dev, :prod->:prod
  name: loki-network
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: loki-network
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: loki-network lokinet
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: loki-network
      name: loki-network
    spec:
      containers:
        - image: 092763672147.dkr.ecr.us-east-1.amazonaws.com/loki/loki-network:latest
          imagePullPolicy: Always
          name: loki-network
          securityContext:
            privileged: true 
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - protocol: UDP 
              containerPort: 1090 
              name: udp-1
            - protocol: UDP 
              containerPort: 1190 
              name: udp-2
      dnsPolicy: ClusterFirst
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status: {}
