variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - test

build:linux:
  image: alpine:latest
  tags:
    - linux
  stage: build
  before_script:
    - apk add --update g++ make cmake linux-headers libcap-dev
  script:
    - make 
  artifacts:
    paths:
      - "lokinet"

#build:windows:
#  tags:
#    - windows
#  stage: build
#  script:
#    - make STATIC_LINK=ON AVX2=OFF JSONRPC=OFF CC=gcc CXX=g++
#  artifacts:
#    paths:
#      - "lokinet.exe"
